# Generated by Django 5.2.7 on 2025-10-30 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Text prompt used to generate image"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Generated image file", upload_to="generated_images/"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When image was generated",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL from API",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Image",
                "verbose_name_plural": "Generated Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
